### PR TITLE
[port_toggle] port_toggle should wait for the ports to really down

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
### Description of PR

Summary:
In current port_toggle test case, after taking all ports down, it only verify that all ports in linux side is down, but it does not check that all ports in DB is really down. We found that there might be a big delay(sometimes 30 seconds) between "linux port down" and "port down in DB". This PR is aimed to fix this issue. 

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?

Verify port status both on linux side and DB side.

#### How did you do it?

1. Add port status check in ansible module show_interface.py
2. Use ansible module show_interface.py to verify that all ports are down from DB side

#### How did you verify/test it?

Manually run port_toggle test case

#### Any platform specific information?

N/A

#### Supported testbed topology if it's a new test case?

N/A

### CODE REVIEW

**Review by liat-grozovik — COMMENTED** [review]
is the operational stats in the show interfaces reflect the linux side or the asic side? IMO the asic side. so why the test does not verify it against the show interfaces? or mayve it does but i cannot tell it from the code.

second, please dont say in our test, this is a case where you need to handle regardless. there might be a diff between linux state and hw state. the show interfaces is supposed IMO to reflect the asic state.
if the test wants to verify both asic and linux i think it is good but the up time for failure should be different and also based on different asics.
so this should be kind of a parameter to the test.

**Comment by Junchao-Mellanox** [comment]
> is the operational stats in the show interfaces reflect the linux side or the asic side? IMO the asic side. so why the test does not verify it against the show interfaces? or mayve it does but i cannot tell it from the code.
> 
> second, please dont say in our test, this is a case where you need to handle regardless. there might be a diff between linux state and hw state. the show interfaces is supposed IMO to reflect the asic state.
> if the test wants to verify both asic and linux i think it is good but the up time for failure should be different and also based on different asics.
> so this should be kind of a parameter to the test.

The "show interfaces" reflects the asic status. 

By the questions "so why the test does not verify it against the show interfaces?", as in this PR, the test already verify the port down state against the show interfaces, do you mean that we should also verify the asic state when taking ports up?

Fixed the description "in our test".

For the up time, we can make it as a parameter for different platforms. Before doing that, we need test the port toggle time on all platforms and get the base line. And we might determine on which SONiC version we should do the test. We probably need a plan for this task.

**Comment by liat-grozovik** [comment]
Hi

I definitely thing we need different time per ASIC according to the table provided in the RN.
Now I am confused.
Can you please provide pseod code for the test flow? Against what is it tested? You mentioned the delay is needed between linux to asic so I assumed validation is against linux and not against the asic.

**Comment by Junchao-Mellanox** [comment]
The old test flow is like this:
1. Take all ports down on sonic side
2. Verify at the linux side, make sure all ports are down
3. Take all ports up on sonic side
4. Wait 60 seconds
5. Verify at the linux side, make sure all ports are up

The test flow in this PR is like:
1. Take all ports down on sonic side
2. Wait 20 seconds
3. Verify at the linux and asic side, make sure all ports are down
4. Take all ports up on sonic side
5. Wait 60 seconds
6. Verify at the linux side, make sure all ports are up

**Review by keboliu — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@Junchao-Mellanox can you please refer to my last comment?

**Comment by Junchao-Mellanox** [comment]
> @Junchao-Mellanox can you please refer to my last comment?

Not quite understand. I think I replied your last comment.

**Comment by Junchao-Mellanox** [comment]
https://github.com/Azure/sonic-mgmt/pull/2548

**Pull request closed without merging**
